name: Validate Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-solution:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 9 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Build the solution
      run: dotnet build
      
  build-image:
    runs-on: ubuntu-latest
    needs: build-solution

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag actions-nuget-report:$(date +%s)

  run-tool:
    runs-on: ubuntu-latest
    needs: build-image

    steps:
    - uses: actions/checkout@v4
    
    - name: Execute the tool
      uses: MathijsNabbe/NugetReporter@main
